version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:8000"
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend